# Generated by Django 4.2 on 2023-05-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favorites'),
        ('shops', '0002_alter_shop_address_alter_shop_closing_time_and_more'),
        ('reviews', '0003_alter_review_user_question'),
        ('menu', '0002_alter_menuitem_description_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Product',
        ),
    ]
