# Generated by Django 4.2 on 2023-05-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(verbose_name='Closing time'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(verbose_name='Opening time'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
